language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: TFi3v+SlN1Ikh+o0coLHuVuv+2Xj4o8SMawiSfq0Dx4QjHfzjrBdsvft8EGEfHMBwCo44Gr8bL65cBH//slCzyBfTlEwaWK3JgKpXv2i2yNmQqAP5hLkZMvUOMaMfKc00vkCutmcwQ4hQhUBi22OVvcxM8ZFz4jSkCM2kPw6Whq9HYBdaMiMfT71twDRnFtWeoUuiICEzXvOLt3WPMRCBwZPDgxEqtZzJVsel1yt8o6IHHCyGykWLxFnMdNxJRwy4/wxTB1iz1AESL4RaFd4rS6vOLYITlNMGfgzGTnwpVzltNT1IjDnsG8WY2DKbEDGFBdLoC6rDch/gDaKe2hZfXyHgoO+T+h7kofcNr7tLtVTt4tRS200o0ply0LImLPIOzV9XOxBa+Ji+6VzaUsEsPhV3SkumrqLTmMdQwRBNodRLcIXRAI1ZP0zBK6HmHXPmHC8xSC2NhTqDDp0gzuOg8XZz4VUpJJSRpkxRe3veG+kesjZP0tVV+2ntsusFh2BBA2rHwwWRM6lCqfWjW/ociupx63fTdWM+BLs3raBHRwL9a+LMEayOEPMmAkDGCMU8JNO9JTbG66awQBvtrBnjeZKxFc1mC3g1HZzZrOGjFEzNhdGKsTuVUWPqJYSBRKRZGvl/sDIaO4FLZGkOtX3gS3RhG2BiZQlCERJl7T0G1o=
  app: boiling-hollows-63273
  on:
    repo: katiebldwn/blog-api-mongoose
